import { useAppStore, type UserProfile } from '@/store/useAppStore';

export type AppLanguage = UserProfile['language'];
type TranslationKey = keyof typeof translations.en;
const translations = {
  en: { home:'Home', journey:'Journey', temples:'Temples', groups:'Groups', profile:'Profile', day:'Day', today:'Today', completed:'Completed', startJourney:'Begin your journey', signIn:'Sign in', continue:'Continue', save:'Save', nearby:'Nearby', search:'Search people & groups', followers:'Followers', following:'Following', follow:'Follow', unfollow:'Following', groupChat:'Group notes', addExpense:'Add expense', markPaid:'Mark paid', trail:'Your Deeksha trail', trailHint:'Your path changes as your Deeksha progresses.', history:'Journey history', noHistory:'Completed Deekshas will appear here.', language:'Language', english:'English', telugu:'తెలుగు', currentLocation:'Current location', offlineMaps:'Offline maps', downloadArea:'Download area for offline use', planning:'Plan a visit', guru:'Guru Swamy', members:'Members', invite:'Invite member', guruApproval:'Guru approval', message:'Message', send:'Send', safety:'Follow temple and Guru guidance.', welcome:'Welcome, Swami', deeksha:'Deeksha', points:'Points', active:'Active' },
  te: { home:'హోమ్', journey:'యాత్ర', temples:'దేవాలయాలు', groups:'సమూహాలు', profile:'ప్రొఫైల్', day:'రోజు', today:'ఈరోజు', completed:'పూర్తయింది', startJourney:'మీ యాత్రను ప్రారంభించండి', signIn:'సైన్ ఇన్', continue:'కొనసాగించు', save:'సేవ్ చేయి', nearby:'సమీపంలో', search:'వ్యక్తులు మరియు సమూహాలను వెతకండి', followers:'అనుచరులు', following:'అనుసరిస్తున్నారు', follow:'అనుసరించు', unfollow:'అనుసరిస్తున్నారు', groupChat:'సమూహ గమనికలు', addExpense:'ఖర్చు జోడించు', markPaid:'చెల్లించినట్లు గుర్తించు', trail:'మీ దీక్ష మార్గం', trailHint:'మీ దీక్ష పురోగతికి అనుగుణంగా మీ మార్గం మారుతుంది.', history:'యాత్ర చరిత్ర', noHistory:'పూర్తయిన దీక్షలు ఇక్కడ కనిపిస్తాయి.', language:'భాష', english:'English', telugu:'తెలుగు', currentLocation:'ప్రస్తుత స్థానం', offlineMaps:'ఆఫ్‌లైన్ మ్యాప్స్', downloadArea:'ఆఫ్‌లైన్ కోసం ప్రాంతాన్ని డౌన్‌లోడ్ చేయండి', planning:'దర్శనాన్ని ప్రణాళిక చేయండి', guru:'గురు స్వామి', members:'సభ్యులు', invite:'సభ్యుడిని ఆహ్వానించు', guruApproval:'గురు ఆమోదం', message:'సందేశం', send:'పంపు', safety:'దేవాలయం మరియు గురు స్వామి మార్గదర్శకాన్ని అనుసరించండి.', welcome:'స్వాగతం, స్వామి', deeksha:'దీక్ష', points:'పాయింట్లు', active:'క్రియాశీలం' },
} as const;

export function translate(language: AppLanguage, key: TranslationKey): string { return translations[language]?.[key] ?? translations.en[key]; }
export function useI18n() { const language=useAppStore(s=>s.profile?.language ?? 'en'); return { language, t:(key:TranslationKey)=>translate(language,key) }; }
