import { useMemo, useState } from 'react';
import { Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import * as Location from 'expo-location';
import { Ionicons } from '@expo/vector-icons';
import { DeityFilter, SAMPLE_TEMPLES, getNearbyTemples } from '@/data/temples';
import { useAppStore } from '@/store/useAppStore';
import { colors, spacing } from '@/theme/colors';
import { useI18n } from '@/i18n';
const filters: Array<DeityFilter | 'All'> = ['All', 'Ayyappa', 'Durga', 'Venkateswara', 'Shiva', 'Hanuman', 'Nookambika'];
export default function MapScreen() { const {t}=useI18n(); const [filter,setFilter]=useState<DeityFilter|'All'>('All'); const [nearby,setNearby]=useState<ReturnType<typeof getNearbyTemples>|null>(null); const saved=useAppStore(s=>s.savedTempleIds); const save=useAppStore(s=>s.saveTemple); const temples=useMemo(()=> (nearby??SAMPLE_TEMPLES).filter(t=>filter==='All'||t.deity===filter),[nearby,filter]); const locate=async()=>{const result=await Location.requestForegroundPermissionsAsync();if(result.status!=='granted')return;const p=await Location.getCurrentPositionAsync({});setNearby(getNearbyTemples(p.coords.latitude,p.coords.longitude,500,filter==='All'?undefined:filter));}; return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.top}><View><Text style={styles.heading}>{t('temples')}</Text><Text style={styles.subtitle}>{nearby?t('nearby'):'Discover pilgrimage centers'}</Text></View><TouchableOpacity onPress={locate} style={styles.near}><Ionicons name="locate" color={colors.background} size={16}/><Text style={styles.nearText}>{t('nearby')}</Text></TouchableOpacity></View><ScrollView horizontal contentContainerStyle={styles.filters} showsHorizontalScrollIndicator={false}>{filters.map(f=><TouchableOpacity key={f} onPress={()=>setFilter(f)} style={[styles.filter,filter===f&&styles.active]}><Text style={[styles.filterText,filter===f&&styles.activeText]}>{f}</Text></TouchableOpacity>)}</ScrollView>{temples.map(t=><View key={t.id} style={styles.card}><View style={styles.cardTop}><View style={styles.copy}><Text style={styles.title}>{t.name}</Text><Text style={styles.meta}>{t.address}, {t.state}</Text><Text style={styles.verified}>{t.verificationStatus.replaceAll('_',' ').toLowerCase()}</Text></View><TouchableOpacity onPress={()=>save(t.id)}><Ionicons name={saved.includes(t.id)?'bookmark':'bookmark-outline'} color={colors.primary} size={24}/></TouchableOpacity></View><TouchableOpacity onPress={()=>Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${t.latitude},${t.longitude}`)}><Text style={styles.directions}>Get directions</Text></TouchableOpacity></View>)}{!temples.length&&<Text style={styles.subtitle}>No temples found for this filter.</Text>}</ScrollView>; }
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md,paddingBottom:40},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},heading:{color:colors.text,fontSize:22,fontWeight:'700'},subtitle:{color:colors.textMuted,fontSize:13,marginTop:3},near:{flexDirection:'row',gap:5,alignItems:'center',backgroundColor:colors.primary,borderRadius:18,paddingHorizontal:12,paddingVertical:8},nearText:{color:colors.background,fontWeight:'700',fontSize:12},filters:{gap:8},filter:{paddingHorizontal:12,paddingVertical:7,borderWidth:1,borderColor:colors.border,borderRadius:20},active:{backgroundColor:'#F0B42920',borderColor:colors.primary},filterText:{color:colors.textMuted,fontSize:12},activeText:{color:colors.primary},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:spacing.md,gap:12},cardTop:{flexDirection:'row',gap:12},copy:{flex:1},title:{color:colors.text,fontWeight:'600',fontSize:15},meta:{color:colors.textMuted,fontSize:12,marginTop:5},verified:{color:colors.success,fontSize:10,textTransform:'capitalize',marginTop:7},directions:{color:colors.primary,fontSize:13,fontWeight:'600'}});
